version: "2"

plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .eslintrc.json
  csslint:
    enabled: true

checks:
  method-complexity:
    enabled: true
  method-lines:
    config:
      threshold: 150
  similar-code:
    enabled: false
  identical-code:
    enabled: true
  argument-count:
    enabled: true
  complex-logic:
    enabled: true

ratings:
  paths:
    - "**.js"
    - "**.jsx"
    - "**.css"
    - "**.less"
    - "**.scss"
    - "**.sss"

exclude_paths:
  - static/**/*
  - src/templates/b16-tomorrow-dark.css
