language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email:
    recipients:
      - renerbaffa@gmail.com
    on_success: always
    on_failure: always
node_js:
  - "9"
git:
  depth: 3
install:
  - npm install -g codecov
script:
  - npm run test && codecov
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  on:
    tags: true
    # branch: develop
